/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arraylist;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Internet
 */
public class ventanaInterfaz extends javax.swing.JFrame {
    
    public int listaNumeros [] = new int [100];
    public int indice = 0;
    

    /**
     * Creates new form ventanaInterfaz
     */
    public ventanaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numero = new javax.swing.JTextField();
        Icono = new javax.swing.JLabel();
        resultado = new javax.swing.JPanel();
        resultado2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        numero.setForeground(new java.awt.Color(0, 0, 0));
        numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroActionPerformed(evt);
            }
        });
        jPanel1.add(numero);

        Icono.setBackground(new java.awt.Color(0, 204, 204));
        Icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arraylist/puntos.gif"))); // NOI18N
        Icono.setMaximumSize(new java.awt.Dimension(50, 50));
        Icono.setMinimumSize(new java.awt.Dimension(50, 50));
        Icono.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(Icono);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 100));

        resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resultado2.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout resultadoLayout = new javax.swing.GroupLayout(resultado);
        resultado.setLayout(resultadoLayout);
        resultadoLayout.setHorizontalGroup(
            resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        resultadoLayout.setVerticalGroup(
            resultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultadoLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, 140));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        btnAgregar.setBackground(new java.awt.Color(61, 193, 211));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAgregar);

        btnMostrar.setBackground(new java.awt.Color(61, 193, 211));
        btnMostrar.setForeground(new java.awt.Color(0, 0, 0));
        btnMostrar.setText("Mostrar");
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMostrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMostrarMouseExited(evt);
            }
        });
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnMostrar);

        btnOrdenar.setBackground(new java.awt.Color(61, 193, 211));
        btnOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        btnOrdenar.setText("Ordenar");
        btnOrdenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrdenarMouseExited(evt);
            }
        });
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel3.add(btnOrdenar);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
       // resultado2.setText (numero.getText());
       
       if (!validarNumeros(numero.getText().trim()))
       {
           JOptionPane.showMessageDialog(rootPane, "El dato es incorrecto");
           numero.setText("");
       }
       else 
        JOptionPane.showMessageDialog(rootPane, "El dato es correcto y a sido agregado");
       listaNumeros [indice]=Integer.parseInt(numero.getText());
       indice++;
       numero.setText("");
    }//GEN-LAST:event_btnAgregarActionPerformed
 
    
    public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9]*");
    }
    
    
    private void numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        String mensaje = " ";
        for (int i=0; i< indice ;i ++)
        {
           mensaje = mensaje + listaNumeros [i]+"-";
           
        }
        resultado2.setText(mensaje);
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        
        for(int i=0; i < (indice-1)  ;i ++)
          {
              for (int j=0;j<(indice-1);j++)
              {
                  if (listaNumeros[j]> listaNumeros [j+1])
                  {
                     int aux= listaNumeros[j];
                      listaNumeros[j]=listaNumeros[j+1];
                      listaNumeros[j+1]= aux;
                  }
              }
          }
        // Mostrar la lista ordenada 
        String mensajeLista = " ";
        for (int i=0;i<indice;i++)
        {
         mensajeLista = mensajeLista + listaNumeros [i]+"-";
        resultado2.setText(mensajeLista);
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    // Cambiando color a los botones  
    
    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        // TODO add your handling code here:
        btnAgregar.setBackground(new java.awt.Color(231, 76, 60));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        // TODO add your handling code here:
         btnAgregar.setBackground(new java.awt.Color(52, 152, 219));
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));   
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnMostrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseEntered
        // TODO add your handling code here:
        
        btnMostrar.setBackground(new java.awt.Color(241, 196, 15));
        btnMostrar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnMostrarMouseEntered

    private void btnMostrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMouseExited
        // TODO add your handling code here:
        
        btnMostrar.setBackground(new java.awt.Color(52, 152, 219));
        btnMostrar.setForeground(new java.awt.Color(0, 0, 0));  
    }//GEN-LAST:event_btnMostrarMouseExited

    private void btnOrdenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseEntered
        // TODO add your handling code here:
        btnOrdenar.setBackground(new java.awt.Color(234, 134, 133));
        btnOrdenar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnOrdenarMouseEntered

    private void btnOrdenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenarMouseExited
        // TODO add your handling code here:
        btnOrdenar.setBackground(new java.awt.Color(52, 152, 219));
        btnOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        
    }//GEN-LAST:event_btnOrdenarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run() {
                new ventanaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icono;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel resultado;
    private javax.swing.JLabel resultado2;
    // End of variables declaration//GEN-END:variables
}
